# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string
pool:
  name: 'default'

steps:

- script: echo $(spid) > spid.txt; echo $(api-key-dev) > api_key.txt
  displayName: 'Save api keys'
- task: Docker@2
  displayName: Build
  inputs:
    command: build
    repository: enigmampc
    tags: enigma-sgx-node
    arguments: --build-arg SECRET_NODE_TYPE=NODE --build-arg SGX_MODE=HW
- task: Docker@2
  displayName: Build
  inputs:
    command: build
    repository: enigmampc
    tags: enigma-sgx-node
    arguments: --build-arg SECRET_NODE_TYPE=BOOTSTRAP

- script: docker-compose -f docker-compose.ci.yaml up -d aesm bootstrap
  displayName: 'Start bootstrap and Aesm'

- script: docker-compose -f docker-compose.ci.yaml up node
  displayName: 'Run integration tests'

- script: docker-compose down
  condition: always()
  displayName: 'Shutdown'