# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string
pool:
  name: 'default'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Enigma Subscription(a8e64295-0d37-4afd-a370-f3b49a744f80)'
    KeyVaultName: 'pipeline-keyvault'
    secretsFilter: '*'
- script: echo $(intel-sgx-spid) > spid.txt; echo $(intel-sgx-api-key-dev) > api_key.txt
  displayName: 'Save api keys'
- task: Docker@2
  displayName: Build
  inputs:
    command: build
    repository: enigmampc
    tags: enigma-sgx-node
    arguments: --build-arg SECRET_NODE_TYPE=NODE --build-arg SGX_MODE=HW
- task: Docker@2
  displayName: Build
  inputs:
    command: build
    repository: enigmampc
    tags: enigma-sgx-node
    arguments: --build-arg SECRET_NODE_TYPE=BOOTSTRAP